services:
  db:
    image: postgres:16-alpine
    container_name: crm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
    volumes:
      - crm_pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  crm_pgdata: